config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # http_method 'path', to: 'controller#action'
  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # post '/users', to: 'users#create'
  # patch '/users/:id', to: 'users#update'
  # delete '/users/:id', to: 'users#destroy'

  # resources :users # makes all the restful routes
  # resources :users, except: [:new,:edit] # makes all routes except the routes in the array
  resources :users do # make only the routes in the array
    resources :chirps, only: [:index]
  end

  resources :chirps, only: [:show]

  resource :session, only: [:new,:create,:destroy]
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :bigint           not null, primary key
#  username              :string           not null
#  email                 :string           not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  political_affiliation :string           not null
#  age                   :integer          not null
#  password_digest       :string           not null
#  session_token         :string           not null
#
class User < ApplicationRecord
    validates :username, :email, :session_token, presence: true, uniqueness: true
    # validates(:username, :email, {presence: true, uniqueness: true})
    validates :political_affiliation, :password_digest, :age, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true # calls getter for self.password, so we need getter

    attr_reader :password
    after_initialize :ensure_session_token
    # before_validation :ensure_session_token # does the same thing as above for our purposes

    # SPIRE:
    # self.find_by_credentials
    # password=
    # is_password?
    # resest_session_token!
    # ensure_session_token

    def password=(password) # gets run automatically during User.new
        self.password_digest = BCrypt::Password.create(password) # sets password_digest to hashed value
        @password = password
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64 # generates random string and sets session_token
    end

    def self.find_by_credentials(username,password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password) # this is_password? is the BCrypt method
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save! # password is always nil when we save! because there is no password col
        self.session_token
    end

    has_many :chirps,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :Chirp

    has_many :likes,
        primary_key: :id,
        foreign_key: :liker_id,
        class_name: :Like

    has_many :liked_chirps,
        through: :likes,
        source: :chirp

    # User.first #grabs the first isntance of user in our database by id
    # User.last #grab the last user by id

    # #find will error out if it doesnt finds what you need 
    # #find_by will not error out but actually return nil if it doesnt find what you need

    # User.find(???) # takes in an id, and is going to return a user by that id
    # #key is the column in the table 
    # #value is what you are looking for
    # User.find_by(key: :value) #search the database for a model that has a key value pair that we passed in 

    # # ! where 

    # User.where(age: 10..20)
    # User.where.not("age <= 11")
    # User.where.not("age <= ?", "11")

    # instructors = ["give_me_wine", "lina_2020", "wakka_wakka"]
    # User.where(username: instructors).order(:username) 
    # User.where(username: instructors).order(username: :desc)

    # User.where("username in (?) ", instructors).order(:username)

    # # ! joins

    # #find all the chirps for the user with the username "charlos_gets_buckets" ???
    # # * jeopardy music*
    # #steps:
    # #1. find the instance we're looking for 
    # # this works 
    # User.find_by(username: "charlos_gets_buckets").chirps
    # #lets do it with one query though...
    # User.select("chirps.*").joins(:chirps).where(username: "charlos_gets_buckets")
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:index,:show,:edit,:update,:delete]

    def new 
        @user = User.new
        render :new
    end

    def edit 
        @user = User.find(params[:id])
        render :edit
    end

    def index
        @users = User.all # get all users from DB and store in users variable
        # every controller action needs to either render or redirect
        # render json: users # rails will turn our users into json
        render :index
    end

    def show
        # just one user
        @user = User.find(params[:id])
        # render json: user
        render :show
        # not necessary - implicit render of the same action name
    end

    def create
        # debugger
        # user = User.new(
        #     email: params[:email],
        #     username: params[:username],
        #     age: params[:age],
        #     political_affiliation: params[:political_affiliation]
        #     # tedious
        # )
        @user = User.new(user_params)
        # creates user instance not in DB
        if @user.save
            # Eventually we will want to log in the user when we create them
            # render json: user
            # redirect_to "/users/#{user.id}" # redirects to show action
            login!(@user)
            redirect_to user_url(@user)
            # creates another HTTP request 
        else
            # render json: user.errors.full_messages, status: 422 # unprocesable entity
            flash.now[:errors] = @user.errors.full_messages
            render :new
            # points to view
        end
    end

    def update
        @user = User.find(params[:id]) # find the user
        if @user.update(user_params)
            # redirect_to "/users/#{user.id}"
            redirect_to user_url(@user)
        else
            render json: @user.errors.full_messages, status: 422
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_url
        # render json: user
    end

    private

    def user_params
        params.require(:user).permit(:age,:username,:email,:political_affiliation,:password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!--1.Action URL; 2.Method 3.Button value-->

<% if type == :new %>
    <% action_url = users_url %>
    <% button_text = "Sign Up" %>
<% else %>
    <% action_url = user_url(user) %>
    <% button_text = "Make better hooman" %>
<% end %>

<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <% if type == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <label id="username" for="username">Username:
        <input type="text" name="user[username]" value="<%= user.username %>">
    </label>
    <br>
    <label for="email">Email:
        <input type="text" name="user[email]" value="<%= user.email %>">
    </label>
    <br>
    <label for="age">Age:
        <input type="text" name="user[age]" value="<%= user.age %>">
    </label>
    <br>
    <label for="political_affiliation">Political Affiliation:
        <input type="text" name="user[political_affiliation]" value="<%= user.political_affiliation %>">
    </label>
    <label>Password
        <input type="password" name="user[password]" value="">
    </label>
    <br>
    <input type="submit" value="<%= button_text  %>">


</form>

app/views/users/_user.html.erb
<% if action == :show %>
    <li><a href="<%=users_url%>">All the hoomans!</a></li>
<% else %>
    <li><a href="<%= edit_user_url(banana) %>">Edit hooman</a></li>
    <li><a href="<%= user_url(banana) %>">User show page</a></li>
    <!--ID passed in implicitely-->
<% end %>
<ul>
    <li><%= banana.username %></li>
    <!-- you will see it!-->
    <li><%= banana.age %></li>
    <li><%= banana.email %></li>
    <li><%= banana.political_affiliation %></li>
</ul>

app/views/users/edit.html.erb
<h1>Make hooman better</h1>

<!--<form action="<%#= user_url(@user) %>" method="POST">
<input type="hidden" name="_method" value="PATCH">
    <label for="username">Username:
        <input type="text" name="user[username]" value="<%#= @user.username %>">
    </label>
    <br>
    <label for="email">Email:
        <input type="text" name="user[email]" value="<%#= @user.email %>">
    </label>
    <br>
    <label for="age">Age:
        <input type="text" name="user[age]" value="<%#= @user.age %>">
    </label>
    <br>
    <label for="political_affiliation">Political Affiliation:
        <input type="text" name="user[political_affiliation]" value="<%#= @user.political_affiliation %>">
    </label>
    <br>
    <input type="submit" value="Edit human">


</form>-->

<%= render "form", {user: @user, type: :edit} %>

app/views/users/index.html.erb
<h1>Here are all of our hoomans!</h1>
<a href="<%= new_user_url %>">Create new user</a>

<ul>

    <% @users.each do |user| %>
    <!-- you will NOT see it!-->
       <!-- <li><%= user.username %></li>
         you will see it!
        <li><%= user.age %></li>
        <li><%= user.email %></li>
        <li><%= user.political_affiliation %></li>-->
        <%= render "user", banana: user, action: :index %>
        <br>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<!--<form action="<%#= users_url %>" method="POST">
    <label for="username">Username:
        <input type="text" name="user[username]" value="<%#= @user.username %>">
    </label>
    <br>
    <label for="email">Email:
        <input type="text" name="user[email]" value="<%#= @user.email %>">
    </label>
    <br>
    <label for="age">Age:
        <input type="text" name="user[age]" value="<%#= @user.age %>">
    </label>
    <br>
    <label for="political_affiliation">Political Affiliation:
        <input type="text" name="user[political_affiliation]" value="<%#= @user.political_affiliation %>">
    </label>
    <br>
    <input type="submit" value="Create human">


</form>-->

<%= render "form", {user: @user, type: :new} %>

app/views/users/show.html.erb
<h1>This is the users show page</h1>
<!-- <ul>
    <li><%#= @user.username %></li>
    <li><%#= @user.age %></li>
    <li><%#= @user.email %></li>
    <li><%#= @user.political_affiliation %></li>
</ul> -->

<%= render "user", {banana: @user, action: :show} %>

<li>
    <form action="<%= user_url(@user) %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE" >
        <input type="submit" value="DESTROY IT!!!!">
    </form>
</li>

<!--"user": file name (_user.hrml.erb)-->
<!--banana: key  -->
<!-- @user: variable saved in that key to be used in your partial-->


<%#=  %> <!-- -> pe -->
<%#  %> <!-- -> er -->