config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # http_method 'path', to: 'controller#action'
  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # post '/users', to: 'users#create'
  # patch '/users/:id', to: 'users#update'
  # delete '/users/:id', to: 'users#destroy'

  # resources :users # makes all the restful routes
  # resources :users, except: [:new,:edit] # makes all routes except the routes in the array
  resources :users do # make only the routes in the array
    resources :chirps, only: [:index]
  end

  resources :chirps, only: [:show]

  resource :session, only: [:new,:create,:destroy]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bluebird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <h2>Welcome to Bluebird, <%= current_user.username %></h2>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Logout">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">Sign up for Bluebird</a>
      <a href="<%= new_session_url %>">Sign in to Bluebird</a>
    <% end %>
    <%= yield %>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
  </body>
</html>